services:
    resource.address:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Address" ]
        tags:      [ { name: "api.resource" } ]

    resource.bar:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Bar" ]
        tags:      [ { name: "api.resource" } ]

    resource.beer:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Beer" ]
        tags:      [ { name: "api.resource" } ]

    resource.city:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\City" ]
        tags:      [ { name: "api.resource" } ]

    resource.color:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Color" ]
        tags:      [ { name: "api.resource" } ]

    resource.country:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Country" ]
        tags:      [ { name: "api.resource" } ]

    resource.hunt.search_filter:
        parent:    "api.doctrine.orm.search_filter"
        arguments: [ { beer: "exact", bar: "exact", hunter: "exact"  } ]

    resource.hunt:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Hunt" ]
        calls:
            -      method:    "initFilters"
                   arguments: [ [ "@resource.hunt.search_filter" ] ]
        tags:      [ { name: "api.resource" } ]

    resource.hunter.search_filter:
        parent:    "api.doctrine.orm.search_filter"
        arguments: [ { username: "exact" } ]

    resource.hunter:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Hunter" ]
        calls:
            -      method:    "initFilters"
                   arguments: [ [ "@resource.hunter.search_filter" ] ]
        tags:      [ { name: "api.resource" } ]

    resource.trophy:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Trophy" ]
        tags:      [ { name: "api.resource" } ]

    resource.trophy_hunter:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\TrophyHunter" ]
        tags:      [ { name: "api.resource" } ]

    resource.vote:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Vote" ]
        tags:      [ { name: "api.resource" } ]

    admin.color:
        class: AppBundle\Admin\ColorAdmin
        arguments: [~, AppBundle\Entity\Color, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Color }

    admin.beer:
        class: AppBundle\Admin\BeerAdmin
        arguments: [~, AppBundle\Entity\Beer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Beer }

    admin.country:
        class: AppBundle\Admin\CountryAdmin
        arguments: [~, AppBundle\Entity\Country, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Country }

    admin.city:
        class: AppBundle\Admin\CityAdmin
        arguments: [~, AppBundle\Entity\City, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: City }

    admin.address:
        class: AppBundle\Admin\AddressAdmin
        arguments: [~, AppBundle\Entity\Address, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Address }

    admin.trophy:
        class: AppBundle\Admin\TrophyAdmin
        arguments: [~, AppBundle\Entity\Trophy, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Trophy }

    admin.bar:
        class: AppBundle\Admin\BarAdmin
        arguments: [~, AppBundle\Entity\Bar, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Bar }

    admin.hunt:
        class: AppBundle\Admin\HuntAdmin
        arguments: [~, AppBundle\Entity\Hunt, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Hunt }

    admin.trophyHunter:
        class: AppBundle\Admin\TrophyHunterAdmin
        arguments: [~, AppBundle\Entity\TrophyHunter, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: TrophyHunter }

    admin.vote:
        class: AppBundle\Admin\VoteAdmin
        arguments: [~, AppBundle\Entity\Vote, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Vote }